=== akarnokd/advance-flow-engine/advance-live-reporter-os/src/l2params.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="paramWeight">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="timeState" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:float" name="tau" minOccurs="0"/>
              <xs:element type="xs:float" name="lambda"/>
              <xs:element type="xs:float" name="delta"/>
              <xs:element type="xs:float" name="wm" minOccurs="0"/>
              <xs:element type="xs:float" name="ws" minOccurs="0"/>
              <xs:element type="xs:float" name="we" minOccurs="0"/>
              <xs:element type="xs:float" name="wn" minOccurs="0"/>
              <xs:element type="xs:float" name="wp" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== akarnokd/advance-flow-engine/advance-live-reporter-os/src/l2params.xml
<?xml version="1.0" encoding="UTF-8"?>
<paramWeight xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="l2params.xsd">
	<timeState id="now_at_hub">
		<tau>0.85</tau>
		<lambda>0.85</lambda>
		<delta>1.2</delta>
	</timeState>
	<timeState id="coming_up">
		<tau>0.85</tau>
		<lambda>0.85</lambda>
		<delta>1.2</delta>
		<wm>0.6</wm>
		<ws>0.3</ws>
		<we>0.1</we>
	</timeState>
	<timeState id="overall">
		<lambda>0.85</lambda>
		<delta>1.2</delta>
		<wn>0.75</wn>
		<wp>0.25</wp>
	</timeState>
</paramWeight>
