=== akarnokd/advance-flow-engine/advance/schemas/flow-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by MESMERiZE (MSM) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="block-description.xsd"/>
	<xs:element name="flow-description">
		<xs:annotation>
			<xs:documentation>The dataflow descriptor format.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="composite-block" type="composite-block">
					<xs:annotation>
						<xs:documentation>The root composite block of the flow description.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="composite-block">
		<xs:annotation>
			<xs:documentation>A complex block description. May contain other blocks, boundary input and output parameters and wire definitions between the contained blocks.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="input" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The optional boundary-parameter of this composite block which lets other internal or external blocks bind to this block.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="input">
							<xs:attribute name="documentation" type="xs:string" use="optional">
								<xs:annotation>
									<xs:documentation>The user-entered documentation of this parameter.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="keywords" use="optional">
								<xs:annotation>
									<xs:documentation>The user-entered keywords for easier finding of this parameter.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:list itemType="xs:string"/>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="output" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The optional boundary parameter of this composite block which lets other internal or external blocks to bind to this block.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="output">
							<xs:attribute name="documentation" type="xs:string" use="optional">
								<xs:annotation>
									<xs:documentation>The user-entered documentation of this parameter.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="keywords" use="optional">
								<xs:annotation>
									<xs:documentation>The user-entered keywords for easier finding of this parameter.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:list itemType="xs:string"/>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="block" type="block" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The optional sub-elements of this block</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="composite-block" type="composite-block" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>An optional composite inner block.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="bind" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The binding definition of internal blocks and/or boundary parameters. You may bind the output of the blocks to many input parameters.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="source-block" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>The source block identifier for the binding. If omitted, the source-parameter refers to the enclosing composite-block's input parameter.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="source-parameter" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>The source parameter identifier of the source-block or the enclosing composite-block's input parameter.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="destination-block" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>The destination block identifier for the binding. If omitted, the destination-parameter refers to the enclosing composite-block's output parameter.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="destination-parameter" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>The destination parameter identifier of the destination-block or the enclosing composite-block's output parameter.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>A constant block containing configuration or other direct values.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:any>
							<xs:annotation>
								<xs:documentation>
								An arbitrary XML content. However, some primitive types should use a predefined structure: 
								&lt;int&gt;&lt;/int&gt; 
								&lt;string&gt;&lt;/string&gt;
								</xs:documentation>
							</xs:annotation>
						</xs:any>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>The constant identifier used by the bindings.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="type" type="xs:anyURI" use="required">
						<xs:annotation>
							<xs:documentation>The schema describing the constant output</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="displayname" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>The optional display name</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="documentation" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>The user-entered documentation of this parameter.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="keywords" use="optional">
						<xs:annotation>
							<xs:documentation>The user-entered keywords for easier finding of this parameter.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:list itemType="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The unique identifier of this block among the current level of blocks.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="documentation" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The user-entered documentation of this composite block.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="keywords" use="optional">
			<xs:annotation>
				<xs:documentation>The user-entered keywords for easier finding of this block.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:list itemType="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="block">
		<xs:annotation>
			<xs:documentation>The concrete block definition</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The unique identifier of this block among the current level of blocks.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The block type identifier referencing a block description.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="documentation" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The user-entered documentation of this composite block.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="keywords" use="optional">
			<xs:annotation>
				<xs:documentation>The user-entered keywords for easier finding of this block.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:list itemType="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/advance-flow-engine/advance/test/flow3_button.xml
<?xml version="1.0" encoding="UTF-8"?>
<flow-description xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/flow-description.xsd">
	<composite-block id="1">
		<block id="b1" type="Button"></block>
		<constant type="advance:string" id="c1"><string>Click click click!</string></constant>
		<block id="b2" type="Gate"/>
		<constant type="advance:string" id="c2"><string>Relay</string></constant>
		<block id='log1' type='Log'/>
		<block id='log0' type='Log'/>
		<block id='merge1' type='Merge'/>
		<block id='text1' type='InputBox'/>
		
		<bind source-block='c1' source-parameter="" destination-block="b1" destination-parameter="title" id="w1"/>
		<bind source-block='c2' source-parameter="" destination-block="b2" destination-parameter="title" id="w2"/>
		<bind source-block='b1' source-parameter='out' destination-block='log0' destination-parameter='in' id="w3"/>
		<bind source-block='b2' source-parameter='out' destination-block='merge1' destination-parameter="1" id='w4'/>
		<bind source-block='log0' source-parameter="out" destination-block="b2" destination-parameter="in" id='w5'/>
		<bind source-block='text1' source-parameter='out' destination-block='merge1' destination-parameter="2" id='w6'/>
		<bind source-block='merge1' source-parameter='out' destination-block='log1' destination-parameter="in" id='w7'/>
	</composite-block>
</flow-description>

=== akarnokd/advance-flow-engine/advance/test/flow1.xml
<?xml version="1.0" encoding="UTF-8"?>
<flow-description xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/flow-description.xsd">
	<composite-block id="1">
	<!-- 
		Compatible case, validation should let this pass. 
		<block id="b1" type="Merge"></block>
		<constant type="advance:string" id="c1"><string>S1</string></constant>
		<constant type="advance:string" id="c2"><string>1</string></constant>
		<bind source-block='c1' source-parameter="" destination-block='b1' destination-parameter="1" id="w1"/>
		<bind source-block='c2' source-parameter="" destination-block='b1' destination-parameter="2" id="w2"/>
	-->
		
	<!-- 
		Common supertype case, validation should let this pass. 
		<block id="b2" type="Merge"></block>
		<block type="IntSink" id="b3"/>
		<constant type="advance:string" id="c3"><string>S1</string></constant>
		<constant type="advance:integer" id="c4"><integer>1</integer></constant>
		<bind source-block='c3' source-parameter="" destination-block='b2' destination-parameter="1" id="w3"/>
		<bind source-block='c4' source-parameter="" destination-block='b2' destination-parameter="2" id="w4"/>
		<bind source-block='b2' source-parameter="out" destination-block="b3" destination-parameter="1" id="w5"/>
    -->
		<!-- Test generic type passing -->
    
		<block type="Singleton" id="b4"/>
		<block type="GetItem" id="b5"/>
		<block type="Sink" id="b6"/>
		<constant type="advance:integer" id="c5"><integer>1</integer></constant>
		<bind source-block='c5' source-parameter="" destination-block="b4" destination-parameter="in" id="w6"/>
		<bind source-block='b4' source-parameter="out" destination-block="b5" destination-parameter="in" id="w7"/>
		<bind source-block='c5' source-parameter="" destination-block="b5" destination-parameter="index" id="w8"/>
		<bind source-block='b5' source-parameter="out" destination-block="b6" destination-parameter="1" id="w9"/>
		
	</composite-block>
</flow-description>
